# 1° COMANDO: C:\Users\nicol\OneDrive\Escritorio\Documentation\Main
# 2° COMANDO: pyuic5 -x "nombre del archivo de qt que es extensión ui" -o "nombre con extensión py"

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top.setStyleSheet("background-color: rgb(18, 21, 26);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_logo = QtWidgets.QLabel(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setMinimumSize(QtCore.QSize(0, 30))
        self.label_logo.setMaximumSize(QtCore.QSize(90, 35))
        self.label_logo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_logo.setMouseTracking(False)
        self.label_logo.setStyleSheet("border-image: url(:/cct/Logo.png);\n"
"border: none;")
        self.label_logo.setText("")
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_3.addWidget(self.label_logo)
        self.Btn_Minimizar = QtWidgets.QPushButton(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Minimizar.sizePolicy().hasHeightForWidth())
        self.Btn_Minimizar.setSizePolicy(sizePolicy)
        self.Btn_Minimizar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Btn_Minimizar.setStyleSheet("border: none;")
        self.Btn_Minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Minimizar.setIcon(icon)
        self.Btn_Minimizar.setIconSize(QtCore.QSize(15, 15))
        self.Btn_Minimizar.setAutoDefault(False)
        self.Btn_Minimizar.setDefault(False)
        self.Btn_Minimizar.setObjectName("Btn_Minimizar")
        self.horizontalLayout_3.addWidget(self.Btn_Minimizar)
        self.Btn_Maximizar = QtWidgets.QPushButton(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Maximizar.sizePolicy().hasHeightForWidth())
        self.Btn_Maximizar.setSizePolicy(sizePolicy)
        self.Btn_Maximizar.setStyleSheet("border: none;\n"
"")
        self.Btn_Maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cct/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Maximizar.setIcon(icon1)
        self.Btn_Maximizar.setObjectName("Btn_Maximizar")
        self.horizontalLayout_3.addWidget(self.Btn_Maximizar)
        self.Btn_Cerrar = QtWidgets.QPushButton(self.frame_top)
        self.Btn_Cerrar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Cerrar.sizePolicy().hasHeightForWidth())
        self.Btn_Cerrar.setSizePolicy(sizePolicy)
        self.Btn_Cerrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Btn_Cerrar.setAutoFillBackground(False)
        self.Btn_Cerrar.setStyleSheet("border: none;\n"
"")
        self.Btn_Cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cct/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Cerrar.setIcon(icon2)
        self.Btn_Cerrar.setIconSize(QtCore.QSize(15, 15))
        self.Btn_Cerrar.setObjectName("Btn_Cerrar")
        self.horizontalLayout_3.addWidget(self.Btn_Cerrar)
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: #12151a;")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Btn_Menu_5 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_5.setStyleSheet("border: none;")
        self.Btn_Menu_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cct/Menú.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Menu_5.setIcon(icon3)
        self.Btn_Menu_5.setIconSize(QtCore.QSize(50, 50))
        self.Btn_Menu_5.setObjectName("Btn_Menu_5")
        self.verticalLayout_3.addWidget(self.Btn_Menu_5)
        self.Btn_Menu_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_4.setFont(font)
        self.Btn_Menu_4.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.Btn_Menu_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Iconos/Productos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Menu_4.setIcon(icon4)
        self.Btn_Menu_4.setIconSize(QtCore.QSize(60, 60))
        self.Btn_Menu_4.setObjectName("Btn_Menu_4")
        self.verticalLayout_3.addWidget(self.Btn_Menu_4)
        self.Btn_Menu_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_1.setFont(font)
        self.Btn_Menu_1.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: 0px solid;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(85, 170, 255);\n"
"}\n"
"")
        self.Btn_Menu_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/cct/Depósito.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Menu_1.setIcon(icon5)
        self.Btn_Menu_1.setIconSize(QtCore.QSize(60, 60))
        self.Btn_Menu_1.setObjectName("Btn_Menu_1")
        self.verticalLayout_3.addWidget(self.Btn_Menu_1)
        self.Btn_Menu_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.Btn_Menu_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_2.setFont(font)
        self.Btn_Menu_2.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: 0px solid;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Iconos/Usuarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Menu_2.setIcon(icon6)
        self.Btn_Menu_2.setIconSize(QtCore.QSize(60, 60))
        self.Btn_Menu_2.setObjectName("Btn_Menu_2")
        self.verticalLayout_3.addWidget(self.Btn_Menu_2)
        self.verticalLayout_2.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.Btn_Menu_3 = QtWidgets.QPushButton(self.frame_left_menu)
        self.Btn_Menu_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Menu_3.setFont(font)
        self.Btn_Menu_3.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(85, 170, 255);\n"
"}")
        self.Btn_Menu_3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/cct/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Menu_3.setIcon(icon7)
        self.Btn_Menu_3.setIconSize(QtCore.QSize(60, 60))
        self.Btn_Menu_3.setObjectName("Btn_Menu_3")
        self.verticalLayout_2.addWidget(self.Btn_Menu_3)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setStyleSheet("border: none;")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widget.setStyleSheet("background-color: rgb(10, 12, 14);\n"
"border: none;")
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Pages_Widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Pages_Widget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.Pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Btn_Menu_1, self.Btn_Menu_2)
        MainWindow.setTabOrder(self.Btn_Menu_2, self.Btn_Menu_3)
        MainWindow.setTabOrder(self.Btn_Menu_3, self.Btn_Menu_5)
        MainWindow.setTabOrder(self.Btn_Menu_5, self.Btn_Maximizar)
        MainWindow.setTabOrder(self.Btn_Maximizar, self.Btn_Cerrar)
        MainWindow.setTabOrder(self.Btn_Cerrar, self.Btn_Menu_4)
        MainWindow.setTabOrder(self.Btn_Menu_4, self.Btn_Minimizar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import iconos_provisorios_rc
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())