# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 786)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMinimumSize(QtCore.QSize(0, 45))
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.Top_Bar.setStyleSheet("background-color: #12151a;\n"
"")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.Top_Bar)
        self.label.setMinimumSize(QtCore.QSize(0, 49))
        self.label.setMaximumSize(QtCore.QSize(200, 63))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/cct/Logo.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: #12151a;")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_toggle.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_toggle.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: none;\n"
"border-radius:20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #23262b;\n"
"}")
        self.btn_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/Menú.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setIconSize(QtCore.QSize(50, 50))
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_3.addWidget(self.btn_toggle)
        self.btn_productos = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_productos.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_productos.setFont(font)
        self.btn_productos.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #23262b;\n"
"}")
        self.btn_productos.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cct/Productos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_productos.setIcon(icon1)
        self.btn_productos.setIconSize(QtCore.QSize(60, 60))
        self.btn_productos.setObjectName("btn_productos")
        self.verticalLayout_3.addWidget(self.btn_productos)
        self.btn_depositos = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_depositos.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_depositos.setFont(font)
        self.btn_depositos.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: 0px solid;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #23262b;\n"
"}")
        self.btn_depositos.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cct/Depósito.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_depositos.setIcon(icon2)
        self.btn_depositos.setIconSize(QtCore.QSize(60, 60))
        self.btn_depositos.setObjectName("btn_depositos")
        self.verticalLayout_3.addWidget(self.btn_depositos)
        self.btn_usuarios = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_usuarios.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_usuarios.setFont(font)
        self.btn_usuarios.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #23262b;\n"
"}")
        self.btn_usuarios.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cct/Usuarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_usuarios.setIcon(icon3)
        self.btn_usuarios.setIconSize(QtCore.QSize(60, 60))
        self.btn_usuarios.setObjectName("btn_usuarios")
        self.verticalLayout_3.addWidget(self.btn_usuarios)
        self.verticalLayout_2.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.btn_exit = QtWidgets.QPushButton(self.frame_left_menu)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("QPushButton {\n"
"color: #b3b3b3;\n"
"background-color: #12151a;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #23262b;\n"
"}")
        self.btn_exit.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/cct/Exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon4)
        self.btn_exit.setIconSize(QtCore.QSize(60, 60))
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_2.addWidget(self.btn_exit)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.slide_bar = QtWidgets.QFrame(self.Content)
        self.slide_bar.setMinimumSize(QtCore.QSize(0, 741))
        self.slide_bar.setMaximumSize(QtCore.QSize(0, 750))
        self.slide_bar.setStyleSheet("background-color: #12151a;")
        self.slide_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_bar.setObjectName("slide_bar")
        self.label_inicio = QtWidgets.QLabel(self.slide_bar)
        self.label_inicio.setGeometry(QtCore.QRect(0, 10, 101, 31))
        self.label_inicio.setStyleSheet("QLabel {\n"
"color: #fff;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QLabel:hover {\n"
"background-color: #23262b;\n"
"}")
        self.label_inicio.setObjectName("label_inicio")
        self.label_deposito = QtWidgets.QLabel(self.slide_bar)
        self.label_deposito.setGeometry(QtCore.QRect(0, 130, 101, 20))
        self.label_deposito.setStyleSheet("color:#fff;\n"
"font-family:Roboto")
        self.label_deposito.setObjectName("label_deposito")
        self.label_productos = QtWidgets.QLabel(self.slide_bar)
        self.label_productos.setGeometry(QtCore.QRect(0, 65, 101, 31))
        self.label_productos.setStyleSheet("QLabel {\n"
"color: #fff;\n"
"\n"
"\n"
"}\n"
"\n"
"QLabel:hover {\n"
"background-color: #23262b;\n"
"}")
        self.label_productos.setObjectName("label_productos")
        self.label_usuarios = QtWidgets.QLabel(self.slide_bar)
        self.label_usuarios.setGeometry(QtCore.QRect(0, 190, 101, 20))
        self.label_usuarios.setStyleSheet("color:#fff;\n"
"font-family:Roboto")
        self.label_usuarios.setObjectName("label_usuarios")
        self.label_exit = QtWidgets.QLabel(self.slide_bar)
        self.label_exit.setGeometry(QtCore.QRect(0, 693, 101, 31))
        self.label_exit.setStyleSheet("QLabel {\n"
"color: #fff;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QLabel:hover {\n"
"background-color: #23262b;\n"
"}")
        self.label_exit.setObjectName("label_exit")
        self.horizontalLayout_2.addWidget(self.slide_bar)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_pages.setStyleSheet("border: none;")
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Pages_Widget = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widget.setStyleSheet("background-color: #1a1e23;\n"
"border: none;")
        self.Pages_Widget.setObjectName("Pages_Widget")
        self.page_productos = QtWidgets.QWidget()
        self.page_productos.setObjectName("page_productos")
        self.label_2 = QtWidgets.QLabel(self.page_productos)
        self.label_2.setGeometry(QtCore.QRect(140, 60, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(17, 115, 255);")
        self.label_2.setObjectName("label_2")
        self.Pages_Widget.addWidget(self.page_productos)
        self.page_depositos = QtWidgets.QWidget()
        self.page_depositos.setObjectName("page_depositos")
        self.label_3 = QtWidgets.QLabel(self.page_depositos)
        self.label_3.setGeometry(QtCore.QRect(120, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(17, 115, 255);")
        self.label_3.setObjectName("label_3")
        self.Pages_Widget.addWidget(self.page_depositos)
        self.page_usuarios = QtWidgets.QWidget()
        self.page_usuarios.setObjectName("page_usuarios")
        self.label_4 = QtWidgets.QLabel(self.page_usuarios)
        self.label_4.setGeometry(QtCore.QRect(70, 60, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(17, 115, 255);")
        self.label_4.setObjectName("label_4")
        self.Pages_Widget.addWidget(self.page_usuarios)
        self.verticalLayout_4.addWidget(self.Pages_Widget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_depositos, self.btn_usuarios)
        MainWindow.setTabOrder(self.btn_usuarios, self.btn_exit)
        MainWindow.setTabOrder(self.btn_exit, self.btn_toggle)
        MainWindow.setTabOrder(self.btn_toggle, self.btn_productos)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_inicio.setText(_translate("MainWindow", "Inicio"))
        self.label_deposito.setText(_translate("MainWindow", "Depósito"))
        self.label_productos.setText(_translate("MainWindow", "Productos"))
        self.label_usuarios.setText(_translate("MainWindow", "Usuarios"))
        self.label_exit.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Productos</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Depósito</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Usuarios</span></p></body></html>"))
import img_oficiales_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
