# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movimiento_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background: #fff;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 40, 431, 321))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(240, 242, 255);\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.subirFoto_btn = QtWidgets.QPushButton(self.frame_3)
        self.subirFoto_btn.setGeometry(QtCore.QRect(250, 220, 160, 25))
        self.subirFoto_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.subirFoto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subirFoto_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(71, 71, 103,180);\n"
"border-radius: 7px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"border: none;\n"
"font-size:13px;\n"
"font-weight: 500;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103);\n"
"color: #fff;\n"
"\n"
"}")
        self.subirFoto_btn.setObjectName("subirFoto_btn")
        self.label_fecha = QtWidgets.QLabel(self.frame_3)
        self.label_fecha.setGeometry(QtCore.QRect(230, 10, 90, 27))
        self.label_fecha.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_fecha.setFont(font)
        self.label_fecha.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_fecha.setObjectName("label_fecha")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 62, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.codigo_producto_input = QtWidgets.QLineEdit(self.frame_3)
        self.codigo_producto_input.setGeometry(QtCore.QRect(20, 100, 170, 25))
        self.codigo_producto_input.setMinimumSize(QtCore.QSize(0, 0))
        self.codigo_producto_input.setMaximumSize(QtCore.QSize(16777215, 25))
        self.codigo_producto_input.setStyleSheet("QLineEdit{\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.codigo_producto_input.setPlaceholderText("")
        self.codigo_producto_input.setObjectName("codigo_producto_input")
        self.label_codigo_producto = QtWidgets.QLabel(self.frame_3)
        self.label_codigo_producto.setGeometry(QtCore.QRect(20, 70, 141, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_codigo_producto.setFont(font)
        self.label_codigo_producto.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_codigo_producto.setObjectName("label_codigo_producto")
        self.descripcion_input = QtWidgets.QTextEdit(self.frame_3)
        self.descripcion_input.setGeometry(QtCore.QRect(230, 160, 170, 43))
        self.descripcion_input.setStyleSheet("border: 1px solid #c1c1c1;\n"
"background-color: #fff;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #000;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px")
        self.descripcion_input.setObjectName("descripcion_input")
        self.label_descripcion = QtWidgets.QLabel(self.frame_3)
        self.label_descripcion.setGeometry(QtCore.QRect(230, 130, 99, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_descripcion.setFont(font)
        self.label_descripcion.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_descripcion.setObjectName("label_descripcion")
        self.tipo_input = QtWidgets.QLineEdit(self.frame_3)
        self.tipo_input.setGeometry(QtCore.QRect(20, 160, 170, 25))
        self.tipo_input.setMinimumSize(QtCore.QSize(0, 0))
        self.tipo_input.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tipo_input.setStyleSheet("QLineEdit{\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.tipo_input.setPlaceholderText("")
        self.tipo_input.setObjectName("tipo_input")
        self.label_tipo = QtWidgets.QLabel(self.frame_3)
        self.label_tipo.setGeometry(QtCore.QRect(20, 130, 84, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_tipo.setFont(font)
        self.label_tipo.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_tipo.setObjectName("label_tipo")
        self.label_motivo = QtWidgets.QLabel(self.frame_3)
        self.label_motivo.setGeometry(QtCore.QRect(230, 70, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_motivo.setFont(font)
        self.label_motivo.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_motivo.setObjectName("label_motivo")
        self.motivo_input = QtWidgets.QLineEdit(self.frame_3)
        self.motivo_input.setGeometry(QtCore.QRect(230, 100, 170, 25))
        self.motivo_input.setMinimumSize(QtCore.QSize(0, 0))
        self.motivo_input.setMaximumSize(QtCore.QSize(16777215, 25))
        self.motivo_input.setStyleSheet("QLineEdit{\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"}\n"
"")
        self.motivo_input.setPlaceholderText("")
        self.motivo_input.setObjectName("motivo_input")
        self.crearprod_btn = QtWidgets.QPushButton(self.frame_3)
        self.crearprod_btn.setGeometry(QtCore.QRect(150, 280, 121, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.crearprod_btn.setFont(font)
        self.crearprod_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crearprod_btn.setStyleSheet("QPushButton{\n"
"background-color: rgba(71, 71, 103);\n"
"color: #fff;\n"
"border-radius:5px;\n"
"font-family:Roboto;\n"
"font-size: 13px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(71, 71, 103,180);\n"
"}")
        self.crearprod_btn.setObjectName("crearprod_btn")
        self.label_egr_ing = QtWidgets.QLabel(self.frame_3)
        self.label_egr_ing.setGeometry(QtCore.QRect(20, 10, 131, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.label_egr_ing.setFont(font)
        self.label_egr_ing.setStyleSheet("font-family: Roboto;\n"
"font-size: 14px;\n"
"margin-top:10px;\n"
"margin-left:10px\n"
"\n"
"")
        self.label_egr_ing.setObjectName("label_egr_ing")
        self.egr_ing_cb = QtWidgets.QComboBox(self.frame_3)
        self.egr_ing_cb.setGeometry(QtCore.QRect(30, 40, 161, 25))
        self.egr_ing_cb.setStyleSheet("padding:0 5px;\n"
"border-radius: 3px;\n"
"font-family:Roboto Lt;\n"
"border: none;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"color: #000;\n"
"\n"
"")
        self.egr_ing_cb.setMaxVisibleItems(3)
        self.egr_ing_cb.setMaxCount(3)
        self.egr_ing_cb.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.egr_ing_cb.setIconSize(QtCore.QSize(16, 0))
        self.egr_ing_cb.setDuplicatesEnabled(False)
        self.egr_ing_cb.setFrame(False)
        self.egr_ing_cb.setObjectName("egr_ing_cb")
        self.egr_ing_cb.addItem("")
        self.egr_ing_cb.addItem("")
        self.fecha_date = QtWidgets.QDateEdit(self.frame_3)
        self.fecha_date.setGeometry(QtCore.QRect(230, 40, 170, 25))
        self.fecha_date.setStyleSheet("\n"
"background-color: #fff;\n"
"border: 0.5px solid #c1c1c1;\n"
"border-radius: 3px;\n"
"padding: 4 5px;\n"
"color: #000;\n"
"font-family:Roboto;\n"
"font-size:13px;\n"
"font-weight: 400;\n"
"margin-left: 10px;\n"
"\n"
"")
        self.fecha_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.fecha_date.setObjectName("fecha_date")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.egr_ing_cb.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subirFoto_btn.setText(_translate("MainWindow", "Subir Imagen"))
        self.label_fecha.setText(_translate("MainWindow", "Fecha"))
        self.label_codigo_producto.setText(_translate("MainWindow", "Código de producto"))
        self.label_descripcion.setText(_translate("MainWindow", "Descripción"))
        self.label_tipo.setText(_translate("MainWindow", "Tipo"))
        self.label_motivo.setText(_translate("MainWindow", "Motivo"))
        self.crearprod_btn.setText(_translate("MainWindow", "Confirmar"))
        self.label_egr_ing.setText(_translate("MainWindow", "Indique La Opción"))
        self.egr_ing_cb.setCurrentText(_translate("MainWindow", "Ingreso"))
        self.egr_ing_cb.setItemText(0, _translate("MainWindow", "Ingreso"))
        self.egr_ing_cb.setItemText(1, _translate("MainWindow", "Egreso"))
import img_oficiales_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
