# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nuevo_producto_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 656)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(700, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet(" background-color: #1a1e23;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(80, 90, 381, 481))
        self.frame_3.setStyleSheet("background-color: #12151a;\n"
"border-radius: 20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 341, 431))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 7, 0, 3)
        self.formLayout.setHorizontalSpacing(38)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.codigo_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.codigo_lbl.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:5px")
        self.codigo_lbl.setObjectName("codigo_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.codigo_lbl)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.codigo_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.codigo_input.setMinimumSize(QtCore.QSize(0, 28))
        self.codigo_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:12px;\n"
"font-weight: 400;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.codigo_input.setPlaceholderText("")
        self.codigo_input.setObjectName("codigo_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.codigo_input)
        self.nombre_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nombre_input.setMinimumSize(QtCore.QSize(0, 28))
        self.nombre_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.nombre_input.setPlaceholderText("")
        self.nombre_input.setObjectName("nombre_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nombre_input)
        self.marca_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.marca_input.setMinimumSize(QtCore.QSize(0, 28))
        self.marca_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.marca_input.setPlaceholderText("")
        self.marca_input.setObjectName("marca_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.marca_input)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cantidad_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.cantidad_input.setMinimumSize(QtCore.QSize(0, 28))
        self.cantidad_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.cantidad_input.setPlaceholderText("")
        self.cantidad_input.setObjectName("cantidad_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cantidad_input)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.desc_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.desc_input.setMinimumSize(QtCore.QSize(0, 28))
        self.desc_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.desc_input.setPlaceholderText("")
        self.desc_input.setObjectName("desc_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.desc_input)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lote_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lote_input.setMinimumSize(QtCore.QSize(0, 28))
        self.lote_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.lote_input.setPlaceholderText("")
        self.lote_input.setObjectName("lote_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lote_input)
        self.venc_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.venc_input.setMinimumSize(QtCore.QSize(0, 28))
        self.venc_input.setStyleSheet("QLineEdit{\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"\n"
"\n"
"QLineEdit:focus{\n"
"}")
        self.venc_input.setPlaceholderText("")
        self.venc_input.setObjectName("venc_input")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.venc_input)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 18px;\n"
"color: #fff;\n"
"margin-top:15px")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.condicion_cbox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.condicion_cbox.setStyleSheet("\n"
"background-color: #23262b;\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"\n"
"\n"
"")
        self.condicion_cbox.setMaxVisibleItems(2)
        self.condicion_cbox.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.condicion_cbox.setDuplicatesEnabled(False)
        self.condicion_cbox.setFrame(True)
        self.condicion_cbox.setObjectName("condicion_cbox")
        self.condicion_cbox.addItem("")
        self.condicion_cbox.addItem("")
        self.condicion_cbox.addItem("")
        self.condicion_cbox.setItemText(2, "")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.condicion_cbox)
        self.subirFoto_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.subirFoto_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.subirFoto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.subirFoto_btn.setStyleSheet("QPushButton{\n"
"background-color: #23262b;\n"
"border-radius: 7px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,10);\n"
"\n"
"}")
        self.subirFoto_btn.setObjectName("subirFoto_btn")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.subirFoto_btn)
        self.fragil_rb = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.fragil_rb.setStyleSheet("QRadioButton{\n"
"\n"
"border-radius: 3px;\n"
"padding: 4 10px;\n"
"color: #fff;\n"
"font-family:Roboto;\n"
"margin-top: 3px;\n"
"border: none;\n"
"font-size:15px;\n"
"font-weight: 400;\n"
"margin-top:15px\n"
"}\n"
"")
        self.fragil_rb.setObjectName("fragil_rb")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fragil_rb)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 10, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: Roboto;\n"
"font-weight: bold;\n"
"font-size: 25px;\n"
"color: #fff;\n"
"background:none;")
        self.label.setObjectName("label")
        self.crearprod_btn = QtWidgets.QPushButton(self.frame)
        self.crearprod_btn.setGeometry(QtCore.QRect(340, 590, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(-1)
        self.crearprod_btn.setFont(font)
        self.crearprod_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crearprod_btn.setStyleSheet("QPushButton{\n"
"background-color: #1173ff;\n"
"color: #fff;\n"
"border-radius:10px;\n"
"font-family:Roboto;\n"
"font-size: 14px\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #45a9f0;\n"
"}")
        self.crearprod_btn.setObjectName("crearprod_btn")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.condicion_cbox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.codigo_lbl.setText(_translate("MainWindow", "CÓDIGO:"))
        self.label_3.setText(_translate("MainWindow", "NOMBRE:"))
        self.label_4.setText(_translate("MainWindow", "MARCA:"))
        self.label_5.setText(_translate("MainWindow", "CANTIDAD:"))
        self.label_6.setText(_translate("MainWindow", "DESCRIPCIÓN:"))
        self.label_8.setText(_translate("MainWindow", "LOTE:"))
        self.label_7.setText(_translate("MainWindow", "VENCIMIENTO:"))
        self.label_9.setText(_translate("MainWindow", "FRAGIL:"))
        self.label_10.setText(_translate("MainWindow", "CONDICIÓN:"))
        self.label_11.setText(_translate("MainWindow", "FOTO:"))
        self.condicion_cbox.setCurrentText(_translate("MainWindow", "Refrigerado"))
        self.condicion_cbox.setItemText(0, _translate("MainWindow", "Refrigerado"))
        self.condicion_cbox.setItemText(1, _translate("MainWindow", "Inflamable"))
        self.subirFoto_btn.setText(_translate("MainWindow", "Subir foto"))
        self.fragil_rb.setText(_translate("MainWindow", "SI"))
        self.label.setText(_translate("MainWindow", "CREAR NUEVO PRODUCTO"))
        self.crearprod_btn.setText(_translate("MainWindow", "Crear Producto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
